name: release
on:
  release:
    types: [published]
jobs:
  main:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build.
        run: |
          depends=$(sed -f scripts/remove-comments.sed -e 's/[^ ]*://g' depends)
          sudo apt-get install $depends
          sudo ./build.sh
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require("./.github/scripts/release.js");
            await script({ github, context, glob, io });
