name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Specify version
        required: true
jobs:
  main:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build.
        run: |
          depends=$(sed -f scripts/remove-comments.sed -e 's/[^ ]*://g' depends)
          sudo apt-get install $depends
          sudo ./build.sh
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require("./.github/scripts/release.cjs");
            const version = process.env.VERSION;
            await script({ version, github, context, glob });
        env:
          VERSION: "${{ github.event.inputs.version }}"
